Add 404 Page
cuhacking/cuHacking-website pull request #31
Opened 2019-12-07 19:13 UTC by MrNickCasey

Instead of redirecting to the homepage on an invalid URL, let's send the user to a well-designed 404 page.

2019-12-07 19:26 UTC, MrNickCasey commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create 404 Page](https://trello.com/c/ZFn9kPIM/212-create-404-page)

2019-12-08 00:22 UTC, walsquared requested changes
Looks DOPE, add this as a final touch

2019-12-08 00:22 UTC, Walsker commented on src/pages/invalid/index.js
> +        <Navbar />
You should add a helmet here to change the title of the page
```javascript
import {Helmet} from 'react-helmet';
// ... in your render function
<Helmet>
   <title>Page not found</title>
</Helmet>

```

2019-12-10 04:39 UTC, Walsker commented
Wave one of applications is about to end, so I had to do this myself.

2019-12-10 04:42 UTC, merged